### ISSUE TITLE
what pytorch version did you use?

### ISSUE THREAD

**Issue by leocd91** [Sudhandar/EfficientNet-Attention-in-a-Siamese-Network#1]
I'm trying your notebook but the results of passing a test input on the model are always nan.

**Comment by Sudhandar** [comment]
Hi, it's working for me. The following is the pytorch version I used, 1.11.0+cu113. Please let me know if it's still not working.

**Comment by leocd91** [comment]
thanks man, just updated my pytorch. nice notebook btw.

**Comment by Sudhandar** [comment]
Thank you!
